import 'package:flutter/material.dart';
import 'package:mirror_logic/domain/theme/visual_theme.dart';

/// Equippable halls. Starter is the original shipped medieval look; the rest
/// follow the theme sheet (forest / neon packs were dropped).
abstract final class ThemeCatalog {
  static const String starterId = 'golden_sun';

  static const List<VisualTheme> all = [
    goldenSun,
    moonlightCastle,
    frozenKingdom,
    lavaForge,
    celestialHeaven,
  ];

  static VisualTheme byId(String id) {
    for (final t in all) {
      if (t.id == id) return t;
    }
    return goldenSun;
  }

  static List<String> get allIds => [for (final t in all) t.id];

  /// Original Mirror Logic hall — cyan beam, dark stone, bronze chrome.
  static const VisualTheme goldenSun = VisualTheme(
    id: starterId,
    name: 'Golden Sun Temple',
    unlockLevel: 1,
    coinPrice: 0,
    woodDeep: Color(0xFF1A0F08),
    woodMid: Color(0xFF2D1B0D),
    woodPlank: Color(0xFF3D2B1F),
    woodLight: Color(0xFF4A3424),
    bronzeDark: Color(0xFF5C3A1E),
    bronze: Color(0xFF8B5E34),
    bronzeMid: Color(0xFFA8723C),
    bronzeLight: Color(0xFFD4AF37),
    bronzeHighlight: Color(0xFFF3CF7A),
    stoneDark: Color(0xFF1E1E1E),
    stone: Color(0xFF2B2B2B),
    stoneLight: Color(0xFF3A3A3A),
    stoneGrout: Color(0xFF141414),
    laserCore: Color(0xFFE8FFFF),
    laserMid: Color(0xFF00F2FF),
    laserGlow: Color(0xFF40C8FF),
    crystal: Color(0xFFA0E8FF),
    crystalDeep: Color(0xFF2090C0),
    parchment: Color(0xFFD4C4A0),
    parchmentDark: Color(0xFFB8A47A),
    parchmentInk: Color(0xFF3A2A18),
    textGold: Color(0xFFF3CF7A),
    textCream: Color(0xFFE5E5E5),
    textMuted: Color(0xFFB8A888),
    torchOrange: Color(0xFFFF8C22),
    torchYellow: Color(0xFFFFD060),
    torchCore: Color(0xFFFFF0A0),
    vineGreen: Color(0xFF2E5A2E),
    wallTint: Color(0xFFFFFFFF),
    floorAsset: 'assets/images/themes/golden_sun/floor.webp',
    wallHAsset: 'assets/images/themes/golden_sun/wall_h.webp',
    wallVAsset: 'assets/images/themes/golden_sun/wall_v.webp',
    accentGlow: Color(0xFF40C8FF),
  );

  static const VisualTheme moonlightCastle = VisualTheme(
    id: 'moonlight_castle',
    name: 'Moonlight Castle',
    unlockLevel: 1,
    coinPrice: 0,
    woodDeep: Color(0xFF0A1020),
    woodMid: Color(0xFF121A30),
    woodPlank: Color(0xFF1A2540),
    woodLight: Color(0xFF243050),
    bronzeDark: Color(0xFF3A4A6A),
    bronze: Color(0xFF5A6E90),
    bronzeMid: Color(0xFF7A90B0),
    bronzeLight: Color(0xFFA8C0E0),
    bronzeHighlight: Color(0xFFD0E4FF),
    stoneDark: Color(0xFF0E1628),
    stone: Color(0xFF162038),
    stoneLight: Color(0xFF223050),
    stoneGrout: Color(0xFF080E18),
    laserCore: Color(0xFFF5FBFF),
    laserMid: Color(0xFF90E0FF),
    laserGlow: Color(0xFF50A0FF),
    crystal: Color(0xFFB8F0FF),
    crystalDeep: Color(0xFF3880D0),
    parchment: Color(0xFFB8C8E0),
    parchmentDark: Color(0xFF8898B8),
    parchmentInk: Color(0xFF101828),
    textGold: Color(0xFFC8DCFF),
    textCream: Color(0xFFE8F0FF),
    textMuted: Color(0xFF8898B8),
    torchOrange: Color(0xFF70A8FF),
    torchYellow: Color(0xFFA8D0FF),
    torchCore: Color(0xFFE0F0FF),
    vineGreen: Color(0xFF3A5080),
    wallTint: Color(0xFF6080C0),
    floorAsset: 'assets/images/themes/moonlight_castle/floor.webp',
    wallHAsset: 'assets/images/themes/moonlight_castle/wall_h.webp',
    wallVAsset: 'assets/images/themes/moonlight_castle/wall_v.webp',
    atmosphereAsset: 'assets/images/themes/moonlight_castle/atmosphere.webp',
    accentGlow: Color(0xFF5080E0),
  );

  static const VisualTheme lavaForge = VisualTheme(
    id: 'lava_forge',
    name: 'Lava Forge',
    unlockLevel: 1,
    coinPrice: 0,
    woodDeep: Color(0xFF140808),
    woodMid: Color(0xFF221010),
    woodPlank: Color(0xFF301818),
    woodLight: Color(0xFF402020),
    bronzeDark: Color(0xFF5C2810),
    bronze: Color(0xFF8B4018),
    bronzeMid: Color(0xFFB05020),
    bronzeLight: Color(0xFFE07030),
    bronzeHighlight: Color(0xFFFFA050),
    stoneDark: Color(0xFF120A0A),
    stone: Color(0xFF1C1010),
    stoneLight: Color(0xFF2A1818),
    stoneGrout: Color(0xFF3A1008),
    laserCore: Color(0xFFFFF8E0),
    laserMid: Color(0xFFFF7030),
    laserGlow: Color(0xFFFF3810),
    crystal: Color(0xFFFFB080),
    crystalDeep: Color(0xFFFF2808),
    parchment: Color(0xFFD4A880),
    parchmentDark: Color(0xFFA87850),
    parchmentInk: Color(0xFF2A1008),
    textGold: Color(0xFFFFA050),
    textCream: Color(0xFFFFE8D0),
    textMuted: Color(0xFFB88868),
    torchOrange: Color(0xFFFF5010),
    torchYellow: Color(0xFFFF9020),
    torchCore: Color(0xFFFFE080),
    vineGreen: Color(0xFF5A2820),
    wallTint: Color(0xFFC05028),
    floorAsset: 'assets/images/themes/lava_forge/floor.webp',
    wallHAsset: 'assets/images/themes/lava_forge/wall_h.webp',
    wallVAsset: 'assets/images/themes/lava_forge/wall_v.webp',
    atmosphereAsset: 'assets/images/themes/lava_forge/atmosphere.webp',
    crystalAsset: 'assets/images/themes/lava_forge/crystal.webp',
    accentGlow: Color(0xFFFF4010),
  );

  static const VisualTheme frozenKingdom = VisualTheme(
    id: 'frozen_kingdom',
    name: 'Frozen Kingdom',
    unlockLevel: 1,
    coinPrice: 0,
    woodDeep: Color(0xFF0C1824),
    woodMid: Color(0xFF142838),
    woodPlank: Color(0xFF1C3850),
    woodLight: Color(0xFF284868),
    bronzeDark: Color(0xFF3A6888),
    bronze: Color(0xFF5A98B8),
    bronzeMid: Color(0xFF78B8D8),
    bronzeLight: Color(0xFFA8DCF0),
    bronzeHighlight: Color(0xFFD8F4FF),
    stoneDark: Color(0xFF183848),
    stone: Color(0xFF285868),
    stoneLight: Color(0xFF407888),
    stoneGrout: Color(0xFF0C2030),
    laserCore: Color(0xFFFFFFFF),
    laserMid: Color(0xFF70F0FF),
    laserGlow: Color(0xFF30C8FF),
    crystal: Color(0xFFB0FFFF),
    crystalDeep: Color(0xFF20A8E0),
    parchment: Color(0xFFC8E8F0),
    parchmentDark: Color(0xFF88B8C8),
    parchmentInk: Color(0xFF102838),
    textGold: Color(0xFFB8E8FF),
    textCream: Color(0xFFF0FAFF),
    textMuted: Color(0xFF88B0C0),
    torchOrange: Color(0xFF40C8F0),
    torchYellow: Color(0xFF90E8FF),
    torchCore: Color(0xFFE0F8FF),
    vineGreen: Color(0xFF3880A0),
    wallTint: Color(0xFF70C8E0),
    floorAsset: 'assets/images/themes/frozen_kingdom/floor.webp',
    wallHAsset: 'assets/images/themes/frozen_kingdom/wall_h.webp',
    wallVAsset: 'assets/images/themes/frozen_kingdom/wall_v.webp',
    atmosphereAsset: 'assets/images/themes/frozen_kingdom/atmosphere.webp',
    accentGlow: Color(0xFF40D0FF),
  );

  static const VisualTheme celestialHeaven = VisualTheme(
    id: 'celestial_heaven',
    name: 'Celestial Heaven Temple',
    unlockLevel: 1,
    coinPrice: 0,
    woodDeep: Color(0xFF1A2030),
    woodMid: Color(0xFF2A3448),
    woodPlank: Color(0xFF3A4860),
    woodLight: Color(0xFF4A5A78),
    bronzeDark: Color(0xFF8A7040),
    bronze: Color(0xFFB89850),
    bronzeMid: Color(0xFFD4B860),
    bronzeLight: Color(0xFFE8D080),
    bronzeHighlight: Color(0xFFFFF0B0),
    stoneDark: Color(0xFFD0D4DC),
    stone: Color(0xFFE4E8F0),
    stoneLight: Color(0xFFF4F6FA),
    stoneGrout: Color(0xFFB8C0D0),
    laserCore: Color(0xFFFFFFF8),
    laserMid: Color(0xFFFFF0B8),
    laserGlow: Color(0xFFE8C870),
    crystal: Color(0xFFFFF8E0),
    crystalDeep: Color(0xFFD4A848),
    parchment: Color(0xFFF0E8D0),
    parchmentDark: Color(0xFFD0C4A0),
    parchmentInk: Color(0xFF283040),
    textGold: Color(0xFFE8D080),
    textCream: Color(0xFFFFFFF8),
    textMuted: Color(0xFFA0A8B8),
    torchOrange: Color(0xFFE8C060),
    torchYellow: Color(0xFFFFE090),
    torchCore: Color(0xFFFFFFF0),
    vineGreen: Color(0xFF6888A0),
    wallTint: Color(0xFFE8E0D0),
    floorAsset: 'assets/images/themes/celestial_heaven/floor.webp',
    wallHAsset: 'assets/images/themes/celestial_heaven/wall_h.webp',
    wallVAsset: 'assets/images/themes/celestial_heaven/wall_v.webp',
    atmosphereAsset: 'assets/images/themes/celestial_heaven/atmosphere.webp',
    accentGlow: Color(0xFFFFE8A0),
  );

  static List<String> get atmosphereAssets => [
    for (final t in all)
      if (t.atmosphereAsset != null) t.atmosphereAsset!,
  ];
}
